In [65]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import r_regression # pearson
import ast
import warnings
import gc
from scipy import sparse

warnings.filterwarnings('ignore') 

pd.set_option("display.max_columns", 100) # ‘None’ value means unlimited.

In [7]:
df = pd.read_json('../output/final/data-comm-light.json',lines=True)

In [8]:
df = df[['book_id','title','user_id','note']]

In [42]:
df['note'] = df['note'].replace('',4.)

In [49]:
df['note'] = df['note'].astype(float)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314009 entries, 0 to 314008
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   book_id  314009 non-null  int64  
 1   title    314009 non-null  object 
 2   user_id  314009 non-null  int64  
 3   note     314009 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 9.6+ MB


In [184]:
pivot = df.pivot_table(index='book_id', columns='user_id', values='note', aggfunc=np.sum, fill_value=0.)

In [185]:
corr = pivot.T.corr()

In [173]:
from sklearn.preprocessing import OneHotEncoder
X = OneHotEncoder().fit_transform(pivot)

In [174]:
X

<4566x109935 sparse matrix of type '<class 'numpy.float64'>'
	with 135286014 stored elements in Compressed Sparse Row format>

In [175]:
similarities = cosine_similarity(X)

KeyboardInterrupt: 

In [78]:
pivot.loc[pivot.index == 1499,:].to_numpy().reshape(-1)

array([[0., 0., 0., ..., 0., 0., 0.]])

In [81]:
pivot.loc[pivot.index == 1508,:].to_numpy().reshape(-1)

array([0., 0., 0., ..., 0., 0., 0.])

In [82]:
from scipy.stats import pearsonr

pearsonr(pivot.loc[pivot.index == 1499,:].to_numpy().reshape(-1),pivot.loc[pivot.index == 1508,:].to_numpy().reshape(-1))

PearsonRResult(statistic=0.03199821323599351, pvalue=3.607649533101816e-08)

In [139]:
df_pearson = pd.DataFrame(index=pivot.index,columns=pivot.index)

In [130]:
df_pearson.loc[df_pearson.index == 1497, 1499] = 1

In [131]:
df_pearson

book_id 1497    1499    1508    1523    1526    1537    1569    1576     \
book_id                                                                   
1497        NaN       1     NaN     NaN     NaN     NaN     NaN     NaN   
1499        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1508        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1523        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1526        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
1462096     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1462133     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1466000     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1467600     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1468104     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

book_id 1578    1579    1594    1627    1655    1675    1686    1689     \
book_id                                                                   
1497        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1499        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1508        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1523        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1526        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
1462096     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1462133     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1466000     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1467600     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1468104     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

book_id 1700    1718    1720    1722    1725    1733    1771    1790     \
book_id                                                                   
1497        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1499        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1508        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1523        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1526        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
1462096     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1462133     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1466000     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1467600     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1468104     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

book_id 1794    1829    1888    1898    1978    2093    2106    2109     \
book_id                                                                   
1497        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1499        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1508        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1523        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1526        NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
1462096     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1462133     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1466000     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1467600     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1468104     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

book_id 2159    2182    2287    2310    2314    2317    2392    2401     \
book_id              

In [140]:
df_pearson.to_numpy()

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [148]:
from tqdm import tqdm

df_pearson = pd.DataFrame(index=pivot.index,columns=pivot.index)
np_pearson = df_pearson.to_numpy()

pivot = pivot.copy()
pivot2 = pivot.copy()
pearson_done = []
i = 0
for row_id, row_values in tqdm(pivot.iterrows()):
    j = -1
    for col_id, col_values in pivot2.iterrows():
        j += 1
        if str(row_id)+' '+str(col_id) in pearson_done:
            continue

        pearson_value = pearsonr(row_values.to_numpy().reshape(-1),col_values.to_numpy().reshape(-1)).statistic
        # df_pearson.loc[df_pearson.index == row_id, col_id] = pearson_value
        # df_pearson.loc[df_pearson.index == col_id, row_id] = pearson_value
        np_pearson[i,j] = pearson_value
        np_pearson[j,i] = pearson_value

        pearson_done.append(str(row_id)+' '+str(col_id))
        pearson_done.append(str(col_id)+' '+str(row_id))
    if i > 0:
        break
    i += 1

df_pearson = pd.DataFrame(np_pearson,index=pivot.index,columns=pivot.index)

1it [00:15, 15.17s/it]


book_id   1497      1499      1508      1523      1526      1537      1569     \
book_id                                                                         
1497          1.0  0.127646  0.022129  0.027633  0.121373  0.073531  0.069362   
1499     0.127646       1.0  0.031998  0.023775  0.113074  0.075898  0.052764   
1508     0.022129  0.031998       NaN       NaN       NaN       NaN       NaN   
1523     0.027633  0.023775       NaN       NaN       NaN       NaN       NaN   
1526     0.121373  0.113074       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096  0.013655 -0.001683       NaN       NaN       NaN       NaN       NaN   
1462133  0.008561 -0.002298       NaN       NaN       NaN       NaN       NaN   
1466000  0.165979  0.091923       NaN       NaN       NaN       NaN       NaN   
1467600  0.048415  0.021452       NaN       NaN       NaN       NaN       NaN   
1468104  0.029757  0.014933       NaN       NaN       NaN       NaN       NaN   

book_id   1576      1578      1579      1594      1627      1655      1675     \
book_id                                                                         
1497     0.027578   0.01883  -0.00205  0.035015  0.027347  0.045071 -0.001424   
1499     0.035562 -0.001728 -0.002215  0.049501   0.04216  0.030416  0.016907   
1508          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1523          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1526          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1462133       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1466000       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1467600       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1468104       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

book_id   1686      1689      1700      1718      1720      1722      1725     \
book_id                                                                         
1497     0.101522  0.147201  0.028795  0.009809  0.038997  0.039007  0.121013   
1499     0.069107  0.151886   0.00596  0.051251  0.057309   0.05139  0.101361   
1508          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1523          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1526          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1462133       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1466000       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1467600       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1468104       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

book_id   1733      1771      1790      1794      1829      1888      1898     \
book_id                                                                         
1497     0.077941  0.158707  0.030237  0.044709  0.023187  0.021083  0.024054   
1499     0.050535  0.108015  0.020303  0.054486  0.019708 -0.001509  0.033607   
1508          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1523          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1526          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1462133       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1466000       NaN       NaN 

In [133]:
df_pearson

book_id   1497      1499      1508      1523      1526      1537      1569     \
book_id                                                                         
1497          1.0  0.127646  0.022129  0.027633  0.121373  0.073531  0.069362   
1499     0.127646       1.0  0.031998  0.023775  0.113074  0.075898  0.052764   
1508     0.022129  0.031998       NaN       NaN       NaN       NaN       NaN   
1523     0.027633  0.023775       NaN       NaN       NaN       NaN       NaN   
1526     0.121373  0.113074       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096  0.013655 -0.001683       NaN       NaN       NaN       NaN       NaN   
1462133  0.008561 -0.002298       NaN       NaN       NaN       NaN       NaN   
1466000  0.165979  0.091923       NaN       NaN       NaN       NaN       NaN   
1467600  0.048415  0.021452       NaN       NaN       NaN       NaN       NaN   
1468104  0.029757  0.014933       NaN       NaN       NaN       NaN       NaN   

book_id   1576      1578      1579      1594      1627      1655      1675     \
book_id                                                                         
1497     0.027578   0.01883  -0.00205  0.035015  0.027347  0.045071 -0.001424   
1499     0.035562 -0.001728 -0.002215  0.049501   0.04216  0.030416  0.016907   
1508          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1523          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1526          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1462133       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1466000       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1467600       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1468104       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

book_id   1686      1689      1700      1718      1720      1722      1725     \
book_id                                                                         
1497     0.101522  0.147201  0.028795  0.009809  0.038997  0.039007  0.121013   
1499     0.069107  0.151886   0.00596  0.051251  0.057309   0.05139  0.101361   
1508          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1523          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1526          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1462133       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1466000       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1467600       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1468104       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

book_id   1733      1771      1790      1794      1829      1888      1898     \
book_id                                                                         
1497     0.077941  0.158707  0.030237  0.044709  0.023187  0.021083  0.024054   
1499     0.050535  0.108015  0.020303  0.054486  0.019708 -0.001509  0.033607   
1508          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1523          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1526          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...           ...       ...       ...       ...       ...       ...       ...   
1462096       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1462133       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1466000       NaN       NaN 

In [109]:
str(1523)

'1523'

In [114]:
df_pearson.index == 1497

array([ True, False, False, ..., False, False, False])

In [116]:
df_pearson.loc[df_pearson.index == 1497, [str(1523)]]

book_id      1523
book_id          
1497     0.027633

In [61]:
similarities.shape

(4566, 4566)

In [62]:
similarities

array([[1.        , 0.1294996 , 0.02400809, ..., 0.16775366, 0.04987864,
        0.03178603],
       [0.1294996 , 1.        , 0.03400655, ..., 0.09401145, 0.02307857,
        0.01715843],
       [0.02400809, 0.03400655, 1.        , ..., 0.03064752, 0.        ,
        0.        ],
       ...,
       [0.16775366, 0.09401145, 0.03064752, ..., 1.        , 0.06482953,
        0.03670567],
       [0.04987864, 0.02307857, 0.        , ..., 0.06482953, 1.        ,
        0.        ],
       [0.03178603, 0.01715843, 0.        , ..., 0.03670567, 0.        ,
        1.        ]])

In [63]:
similarities[0]

array([1.        , 0.1294996 , 0.02400809, ..., 0.16775366, 0.04987864,
       0.03178603])

In [183]:
np1 = np.array([[0,1,1,0,0,0,0,0,0,0],[0,1,0,1,0,0,1,0,0,0],[0,1,1,1,1,0,0,0,1,0]])
np2 = np.array([[1,0,1],[0,1,1],[0,0,0]])
cosine_similarity(np2)

array([[1. , 0.5, 0. ],
       [0.5, 1. , 0. ],
       [0. , 0. , 0. ]])

In [188]:
pivot = df.pivot_table(index='book_id', columns='user_id', values='note')

In [189]:
pivot

user_id  23       31       87       106      107      108      118      \
book_id                                                                  
1497         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1499         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1508         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1523         5.0      NaN      NaN      NaN      NaN      NaN      NaN   
1526         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
...          ...      ...      ...      ...      ...      ...      ...   
1462096      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1462133      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1466000      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1467600      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1468104      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

user_id  135      140      143      159      167      170      177      \
book_id                                                                  
1497         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1499         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1508         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1523         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1526         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
...          ...      ...      ...      ...      ...      ...      ...   
1462096      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1462133      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1466000      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1467600      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1468104      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

user_id  180      181      237      240      255      281      286      \
book_id                                                                  
1497         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1499         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1508         NaN      NaN      NaN      NaN      5.0      NaN      NaN   
1523         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1526         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
...          ...      ...      ...      ...      ...      ...      ...   
1462096      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1462133      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1466000      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1467600      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1468104      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

user_id  287      293      309      317      334      337      338      \
book_id                                                                  
1497         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1499         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1508         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1523         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1526         NaN      NaN      NaN      NaN      NaN      NaN      NaN   
...          ...      ...      ...      ...      ...      ...      ...   
1462096      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1462133      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1466000      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1467600      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1468104      NaN      5.0      NaN      NaN      NaN      NaN      NaN   

user_id  359      383      396      434      440      450      455      \
book_id                                                                  


In [190]:
df_comm['user_id'].value_counts()

339894     705
47258      571
5865       570
46264      547
152189     496
          ... 
1241667      1
1006429      1
1018007      1
144058       1
231635       1
Name: user_id, Length: 29629, dtype: int64